----
title: Altérations
categories: [technique]
date: 2026-02-07
format:
  html: default
  pdf: default
theme: sketchy
----

Les altérations permettent de changer la hauteur d’une note, ce qui permet d’obtenir une note qui n’est pas présente naturellement sur l’harmonica, ou bien d’obtenir un effet consistant à démarrer une note plus bas et relâcher 
immédiatement l’altération pour entendre la note prévue. Sauf mention du contraire, les explications données ici concernent l’harmonica diatonique (blues) 10 trous accordage Richter.

Dans cet article, je présente d’abord une technique permettant l’obtention des altérations, puis je donne des exemples d’utilisation, et enfin je donne quelques informations sur les altérations pour d’autres types d’harmonica 
(diatonique avec un accordage alternatif, diatonique semi-valvé, chromatique, tremolo ou octave).

# La technique d’altération

Le principe des altérations est de modifier la pression de l’air dans l’harmonica afin de faire vibrer plus rapidement l’anche opposée au sens de respiration. En effet, prenons par exemple un harmonica en C. Une aspiration normale
dans le canal 4 produit la note Ré, alors que souffler normalement dans le canal 4 produit un Do. Si on altère (j’explique la technique juste après) en aspirant, ce n’est plus l’anche de Ré qui vibre, mais celle de Do (alors qu’on aspire)
qui vibre plus rapidement, produisant une note plus aigüe que le Do (mais plus grave que le Ré). En revanche la technique d’altération utilisée alors qu’on souffle dans le canal 4 va faire vibrer plus rapidement l’anche de Ré
(alors qu’elle est déclenchée normalement en aspirant) produisant une note plus aigüe que le Ré (Ré dièse ou mi bémol).

::: {.callout-note collapse=true}
## Exercice 1 - sans harmonica
Il est important de comprendre qu’une mauvaise posture …
:::
